name: Build and Upload Executable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Executable
      run: pyinstaller --add-data "src/entry_datasm:src/entry_datas" scapper.py

    - name: Rename dist Folder
      run: mv dist ts_scrapper

    - name: Upload Renamed dist Folder
      uses: actions/upload-artifact@v2
      with:
        name: new-dist-folder
        path: ts_scrapper/
